version: "3.9"

services:
  alephium:
    image: alephium/alephium:v3.13.0
    restart: unless-stopped
    ports:
      - 19973:19973/tcp
      - 19973:19973/udp
      - 127.0.0.1:20973:20973
      - 127.0.0.1:21973:21973
      - 127.0.0.1:22973:22973
    environment:
      - ALEPHIUM_LOG_LEVEL=DEBUG
      - ALEPHIUM_ENABLE_DEBUG_LOGGING=true
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./devnet.conf:/alephium-home/.alephium/user.conf
    healthcheck:
      test: curl --fail http://127.0.0.1:22973/wallets || exit 1
      interval: 3s
      retries: 10
      timeout: 45s
