{
 "title": "Explorer Backend Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Number of Requests Per Second",
   "type": "graph",
   "description": "Number of requests per second, grouped by endpoint",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(explorer_backend_requests_total{app=\"explorer-backend\"}[1m])) by (path)",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "sum(irate(explorer_backend_requests_total{app=\"explorer-backend\"}[1m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Failed Requests Count",
   "type": "graph",
   "description": "Failed requests count in last 1 minute",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(explorer_backend_responses_total{app=\"explorer-backend\",status=\"5xx\"}[1m])) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(explorer_backend_responses_duration_bucket{app=\"explorer-backend\"}[1m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(explorer_backend_responses_duration_bucket{app=\"explorer-backend\"}[1m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(irate(explorer_backend_responses_duration_bucket{app=\"explorer-backend\"}[1m])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "sum(irate(explorer_backend_responses_duration_sum{app=\"explorer-backend\"}[1m])) / sum(irate(explorer_backend_responses_duration_count{app=\"explorer-backend\"}[1m]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Average Request Duration By Endpoint",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(explorer_backend_responses_duration_sum{app=\"explorer-backend\"}[1m])) by (path)) / (sum(irate(explorer_backend_responses_duration_count{app=\"explorer-backend\"}[1m])) by (path))",
     "legendFormat": "{{path}}"
    }
   ]
  }
 ]
}