name: Release

on:
  push:
    tags: [ "v[0-9]+.[0-9]+.[0-9]+*" ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: sbt
      - name: Get the version
        id: get_version
        run: |
          version=$(echo ${GITHUB_REF/refs\/tags\//} | cut -c 2-)
          echo "VERSION=$version" >> $GITHUB_OUTPUT
        shell: bash
      - run: sbt app/assembly
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          release_name: v${{ steps.get_version.outputs.VERSION }}
          body: Some solid code
          draft: false
          prerelease: false
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/target/scala-2.13/explorer-backend-${{ steps.get_version.outputs.VERSION }}.jar
          asset_name: explorer-backend-${{ steps.get_version.outputs.VERSION }}.jar
          asset_content_type: application/java-archive
